### ISSUE TITLE
Request for amendment

### ISSUE THREAD

**Issue by JosephChenHub** [ChocoWu/Awesome-Scene-Graph-Generation#4]
nice job! but our work ECCV24's work [[Expanding Scene Graph Boundaries: Fully Open-vocabulary Scene Graph Generation via Visual-Concept Alignment and Retention](https://github.com/gpt4vision/OvSGTR)] should be categorised to non-LLM based .

**Comment by ChocoWu** [comment]
Very nice work, and I have corrected it.
